image: openjdk:8

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules
        - .gradle/wrapper
        - .gradle/caches
stages:
    - build
    - test
    - package
    - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew
    - ./gradlew yarn_install -PnodeInstall --no-daemon

gradle-build:
    stage: build
    script:
        - ./gradlew compileJava -x check -PnodeInstall --no-daemon
gradle-test:
    stage: test
    script:
        - ./gradlew test -PnodeInstall --no-daemon
    artifacts:
        paths:
            - build/reports/tests/*
gradle-front-test:
    stage: test
    script:
        - ./gradlew yarn_test -PnodeInstall --no-daemon
    artifacts:
        paths:
            - build/test-results/karma/*

# REPLACED the following
#gradle-repackage:
#    stage: package
#    script:
#        - ./gradlew bootRepackage -Pprod -x check -PnodeInstall --no-daemon
#    artifacts:
#        paths:
#            - build/libs/*.war
gradle-repackage:
    image: ggotti/jhipster-gitlab-java-docker-builder
    stage: package
    services:
    - docker:dind
    variables:
        CONTAINER_BASE: test.private.repo
        CONTAINER_NAME: test.private.repo/gateway
    before_script:
    -  docker login -u admin -p $DOCKER_REPO_PWD $CONTAINER_BASE
    script:
        - ./gradlew -Pprod -x check -PnodeInstall --no-daemon bootRepackage buildDocker -x test -x check
        - docker tag gateway $CONTAINER_NAME:latest
        - docker push $CONTAINER_NAME:latest

# Added the following Gitlab build trigger to call the other function
trigger_build:
    stage: deploy
    before_script:
        - echo "Override Before Script"
    variables:
    script:
        - "curl -X POST -F token=$GITLAB_TOKEN -F ref=master -F \"variables[SERVICE]=gateway-app\" https://gitlab.your-hosted-instance.path/api/v3/projects/678/trigger/builds"
