# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Rancher

jhipster:
    security:
        authentication:
            jwt:
                secret: SUPER_SECRET_JWT
